"""empty message

Revision ID: 11f0faec86d5
Revises: 8087bca37409
Create Date: 2017-05-25 08:47:02.617887

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '11f0faec86d5'
down_revision = '8087bca37409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
                    sa.Column(
                        'id',
                        sa.Text(),
                        server_default=sa.FetchedValue(),
                        nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.execute(
        'CREATE TRIGGER trigger_claim_genid BEFORE INSERT ON claim FOR EACH ROW EXECUTE PROCEDURE unique_short_id();'
    )
    op.create_table('argument_link',
                    sa.Column('claim_id', sa.Text(), nullable=False),
                    sa.Column('argument_id', sa.Text(), nullable=False),
                    sa.Column('is_for', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['argument_id'],
                        ['claim.id'],),
                    sa.ForeignKeyConstraint(
                        ['claim_id'],
                        ['claim.id'],),
                    sa.PrimaryKeyConstraint('claim_id', 'argument_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('argument_link')
    op.drop_table('claim')
    # ### end Alembic commands ###
