"""empty message

Revision ID: 8087bca37409
Revises: ff2de6986eba
Create Date: 2017-05-15 09:31:19.169986

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8087bca37409'
down_revision = 'ff2de6986eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dwd_user',
                  sa.Column(
                      'created',
                      sa.DateTime(),
                      server_default=sa.text('now()'),
                      nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dwd_user', 'created')
    # ### end Alembic commands ###
